apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-api
  labels:
    app: predict-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: predict-api
  template:
    metadata:
      labels:
        app: predict-api
    spec:
      containers:
        - name: api
          image: madhupdevops/python-api-azodha:latest
          ports:
            - containerPort: 8000
