apiVersion: v1
kind: Service
metadata:
  name: predict-api-service
spec:
  selector:
    app: predict-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort

